src/Response/CsvResponse.php
**Reason for the change:**
I'm trying to implement a SHIPMENT_ORDERS_GET request. Collmex doesn't return a specific response type, so I'm not able to write an according and generic class for it.
This option gives me the ability to handle the returned data myself.
=> added option to get the original raw csv collmex response string

README.md
- fix a few typos
- break the lines at 80 characters
- drop the instructions for installing with development dependencies
(which is the default in current Composer versions)
- add a version restriction to the `composer require` as unbounded
dependencies are not recommended
- use single quotes in the PHP code
- drop the [] and () for links as links are rendered automatically
in Markdown
=> [CLEANUP] Clean up the installation instructions and the README

.travis.yml
This ensures that our dependency versions given in the composer.json always
provide a working set of packages.
=> [TASK] Test with both latest and oldest dependencies

composer.json
As this library has not been tested with PHP 7.3 yet, the composer.json
should only state compatibility with PHP up to 7.2.x.
(Using ^7.0.0 would allow PHP 7.x.y. So the requirement needs to be up
to ~7.2.0, which is 7.2.x.)
=> [TASK] Don't announce PHP 7.3 compatibility

.travis.yml
Now the order of entries in .travis.yml reflects the ordner in which
TravisCI executes things.
Also drop an unneeded pair of quotes around the Composer cache path.
=> [CLEANUP] Reorder the build steps in .travis.yml

src/Client/Curl.php, src/CollmexServiceProvider.php, src/Type/Customer.php, src/Type/CustomerGet.php, src/Type/Invoice.php, src/Type/InvoiceGet.php, src/Type/Login.php, src/Type/Member.php, src/Type/Message.php, src/Type/NewObject.php, src/Type/Revenue.php, src/Type/SalesOrderGet.php, src/Type/Subscription.php, src/Type/SubscriptionGet.php, src/Type/Validator/Date.php, src/Type/Validator/DateOrEmpty.php, src/Type/Validator/TimeInterval.php, src/Type/Validator/ValidatorInterface.php, tests/Csv/SimpleGeneratorTest.php, tests/Csv/SimpleParserTest.php, tests/Filter/Utf8ToWindows1252Test.php, tests/Filter/Windows1252ToUtf8Test.php, tests/Regression/Github/10/Issue10Test.php, tests/Regression/Github/2/Issue2Test.php, tests/Type/SubscriptionTest.php, tests/TypeFactoryTest.php
As this library required PHP >= 5.6, using the short array syntax
will be safe.
=> [CLEANUP] Switch to the short array syntax

.travis.yml
Travis already always does a composer update, and the composer install
already is done in the install section of the .travis.yml.
=> [TASK] Drop rendundant composer update and install from .travis.yml

composer.json, tests/Csv/LeagueCsvGeneratorTest.php, tests/Csv/SimpleGeneratorTest.php, tests/Csv/SimpleParserTest.php, tests/Filter/Utf8ToWindows1252Test.php, tests/Filter/Windows1252ToUtf8Test.php, tests/ResponseTest.php, tests/Type/SubscriptionTest.php, tests/Type/Validator/DateOrEmptyTest.php, tests/Type/Validator/DateTest.php, tests/Type/Validator/TimeIntervalTest.php, tests/TypeFactoryTest.php
Also add this namespace the the dev autoload section in the
composer.json.
Also add imports as needed and fix an incorrect type annotation.
The regression tests currently do not have a suitable namespace yet;
they need to be integrated into the other tests firsts.
=> [CLEANUP] Have a distinct namespace for the tests

CHANGELOG.md, composer.json
As this library should be usable for a wide range of projects that
also might have other library dependencies, this library's dependencies
should be as lenient as possible in their version requirements, and
use ^ version constraints.
Also update the development dependencies to their latest version.
=> [TASK] Make the runtime dependencies more lenient

README.md, src/Type/BalanceGet.php
I've tested the request manually with  `client_id`, `business_year` and `account_id`. However I am not sure how the packages maps those attributes to the fields mentioned in the [collmex balance-get doku](https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Salden). So maybe someone else should also verify it is working.
How is the mapping done? @mjaschen could you give me a brief overview or point me to the relevant code parts?
=> Add "ACCBAL_GET" alias BalanceGet

CHANGELOG.md
- consistently use hyphens for list items
- use code formatting for a class name
- fix the capitalization of a word
=> [CLEANUP] Clean up the changelog formatting

composer.json
This makes sure the class `\Illuminate\Support\ServiceProvider` is
defined.
=> [TASK] Add laravel/framework as a dev dependency

src/Client/Curl.php, src/Response/ResponseFactory.php, src/Response/ZipResponse.php, src/Type/AbstractType.php
Now the annotations exactly match the `throw` calls in the methods.
=> [CLEANUP] Streamline the `@throws` annotation

tests/Csv/LeagueCsvGeneratorTest.php
`markTestSkipped` already exits the method. So a return after that
is not needed.
=> [CLEANUP] Remove redundant return from a test case

src/CollmexServiceProvider.php
This allows us to skip whitelisting the offending file in Psalm.
=> [CLEANUP] Add missing return type annotations

.travis.yml, README.md, composer.json
This commit is only about updating the requirements.
Using PHP 7 features and re-enabled Psalm will go into separate commits.
Closes #104
=> [TASK] Drop support for PHP < 7.0

.travis.yml, composer.json
Move `roave/security-advisories` to the bottom as this dependency
is different to the other dependencies: It does not provide code,
but blocks insecure versions from being installed.
In addition, keeping this dependency at the bottom allows other
dependencies being removed or added without have to care about
trailing commas after arrays in the composer.json.
This PR should only be merged after #106 has been merged.
=> [CLEANUP] Reorder the dev dependencies

.travis.yml, composer.json
Now the settings `prefer stable` and `prefer dist` are located in the
`composer.json`, not as command-line argument to `composer update` anymore.
This only affects when using the package stand-alone (i.e., during development),
not when the package is used as a dependency.
This PR should only be merged after #106 has been merged.
=> [CLEANUP] Shorten the composer install in the TravisCI build

composer.json
For example, `^2.0` is just as good as `^2.0.0`, but more succinct.
=> [CLEANUP] Use shorter version constraints in the composer.json

composer.json
Now the dependencies are:
- "neitanod/forceutf8": "^2.0",
- "symfony/finder": "^4.0",
- "symfony/http-foundation": "^4.0"
This is a breaking change for projects that still use older version of these
libraries.
Closes #117
=> [TASK] Raise the production dependencies

composer.json
Now all dependencies (except for PHPUnit, which will be a separate change)
are at their current major release.
This does not affect projects using `mjaschen/collmex` as a dependency.
=> [TASK] Raise the dev dependencies

tests/Csv/LeagueCsvGeneratorTest.php, tests/Csv/LeagueCsvParserTest.php, tests/Csv/SimpleGeneratorTest.php, tests/Csv/SimpleParserTest.php, tests/Filter/Utf8ToWindows1252Test.php, tests/Filter/Windows1252ToUtf8Test.php, tests/ResponseTest.php, tests/Type/SubscriptionTest.php, tests/Type/Validator/DateOrEmptyTest.php, tests/Type/Validator/DateTest.php, tests/Type/Validator/TimeIntervalTest.php, tests/TypeFactoryTest.php
- Make `setUp` and `tearDown` protected as the corresponding methods
in the base class are protected as well, and there is no need to
make these methods public.
- Delete `tearDown` methods that do nothing else than unset the
subject. Current versions of PHP do not need this anymore for
the garbage collector.
=> [CLEANUP] Streamline setUp and tearDown in the tests

composer.json, phpcs.xml.dist
The configuration currently includes only those sniffs that do not
create any warnings or errors with the current code base.
The sniffs that make sense, but do not pass yet are commented-out.
New sniffs will be added to the configuration together with the corresponding
code cleanup.
=> [FEATURE] Add a configuration for PHP_CodeSniffer

src/Type/AbstractType.php
This is required for PSR-2 compatibility.
=> [CLEANUP] Use proper camelCase for all method names

.php_cs.dist, tests/Csv/LeagueCsvGeneratorTest.php, tests/Csv/LeagueCsvParserTest.php, tests/Csv/SimpleGeneratorTest.php, tests/Csv/SimpleParserTest.php, tests/Filter/Utf8ToWindows1252Test.php, tests/Filter/Windows1252ToUtf8Test.php, tests/ResponseTest.php
This will also catch type mismatches.
=> [CLEANUP] Use strict checks in the unit tests

.php_cs.dist, tests/Unit/Csv/LeagueCsvGeneratorTest.php, tests/Unit/Csv/LeagueCsvParserTest.php, tests/Unit/Csv/SimpleGeneratorTest.php, tests/Unit/Csv/SimpleParserTest.php, tests/Unit/Filter/Utf8ToWindows1252Test.php, tests/Unit/Filter/Windows1252ToUtf8Test.php, tests/Unit/ResponseTest.php, tests/Unit/Type/SubscriptionTest.php, tests/Unit/Type/Validator/DateOrEmptyTest.php, tests/Unit/Type/Validator/DateTest.php, tests/Unit/Type/Validator/TimeIntervalTest.php, tests/Unit/TypeFactoryTest.php
As the methods are static, the calls should be static, too.
And as the methods are not expected to be overwritten in subclasses,
`static::` is not needed, and `self::` will suffice.
=> [CLEANUP] Always use self:: for calling the PHPUnit assertions

tests/Unit/Response/CsvResponseTest.php
This test is about the `CsvResponse` class and should be named
accordingly.
Also move the test into the `Response` sub-namespace so that the test
namespace structure matches the namespace structure of the tested classes.
=> [CLEANUP] Rename ResponseTest to CsvResponseTest

tests/Integration/Response/ZipResponseTest.php
The test is an integration tests and hence should not use stubs.
=> [TASK] Use a real parser instance in ZipResponseTest

src/Response/CsvResponse.php, src/Response/ZipResponse.php
Method visibility should be as narrow as possible to help static
code analysis, and to make refactorings easier.
=> [CLEANUP] Reduce the visibility of some Response methods

src/Response/ZipResponse.php, tests/Integration/Response/ZipResponseTest.php
`ZipArchive::open()` returns error codes on failure, not `false`.
Also polish the exception message a bit.
=> [BUGFIX] Throw an exception if a ZIP cannot be opened

src/Csv/FormatInterface.php, src/Csv/SimpleGenerator.php, src/Csv/SimpleParser.php, tests/Unit/Csv/SimpleGeneratorTest.php, tests/Unit/Csv/SimpleParserTest.php
As the delimiter and enclosure are not subject to change for Collmex,
we can hardcode them to reduce code complexity.
Closes #166
=> [TASK] Hard-code the CSV delimiter and enclosure

src/Response/Exception/InvalidZipResponseException.php, src/Response/ZipResponse.php, tests/Integration/Response/ZipResponseTest.php
(fixes #124)
If a Zip response doesn't contain the CSV part, an
`InvalidZipResponseException` is thrown as such a response is invalid
regarding to the Collmex documentation[1]. The previous behaviour was
to silently accept such an invalid response and return `null`.
[1] https://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Rechnungen
=> change behaviour for invalid Zip responses

src/Filter/FilterInterface.php, src/Filter/Utf8ToWindows1252.php, src/Filter/Windows1252ToUtf8.php
This method has been deprecated in the past.
=> [TASK] Remove the deprecated FilterInterface::filter method

src/Type/AbstractType.php
Now that there is only one generator, there is no need to be flexible
about the kind of generator that is used.
Fixes #175
=> [TASK] Drop the generator paramter from the AbstractType constructor

src/Request.php
There is only one parser here, and there is no need for this
flexibility now.
Fixes #176
=> [TASK] Drop the parser parameter from the request Constructor

.gitattributes
This should reduce the size of the packages that are installed with the
`--prefer-dist` option (which is the default).
=> [BUGFIX] Keep development files out of Composer packages

tests/Unit/Filter/Utf8ToWindows1252Test.php, tests/Unit/Filter/Windows1252ToUtf8Test.php
The tests should be for `filterString`, not for the removed
`filter` method.
=> [BUGFIX] Fix the tested function in the FilterTests

src/Response/ZipResponse.php, tests/Integration/Response/ZipResponseTest.php
When trying to run DeliveryGet with request for bill of delivery I got this error:
```
Fatal error:  Uncaught TypeError: file_get_contents() expects parameter 1 to be a valid path, object given in C:\xampp\htdocs\perola-api\vendor\mjaschen\collmex\src\Response\ZipResponse.php:82
Stack trace:
#0 C:\xampp\htdocs\perola-api\vendor\mjaschen\collmex\src\Response\ZipResponse.php(82): file_get_contents(Object(Symfony\Component\Finder\SplFileInfo))
```
This fix accesses the pathName property to get a valid path for file_get_contents.
=> bugfix: csv response in unzipped zip-file not accessible

phpcs.xml.dist
PSR-12 (which we use) has superseded PSR-2.
(In the code fixer configuration, we are still referring to the
PSR-2 fixer set as long as no PSR-12 fixer set is available.)
=> [TASK] Drop PSR-2 from the code sniffing configuration

src/Type/ProductionOrder.php
I misspelled the field `bill_of_material_version`, so this is the fix... sorry for that!
Sad enough: it's a breaking change
=> bugfix: fixed typo in ProductionOrder type

composer.json
As this package is a library, it should not limit is compatibility
with different versions of Symfony without need.
Now we support all versions of Symfony that still receive security
updates (as listed on https://symfony.com/releases), not more and
not less.
=> [TASK] Support all security-supported Symfony versions

src/Type/CustomerOrder.php, src/Type/Invoice.php
Hi Marcus,
just talked with Collmex about the fact that the default "Schlusstext" Baustein is not automatically set. Regarding to this I've changed the default param value of the regarding field. Tested and works now.
Collmex answer:
In diesem Datensatz ist das Feld für den Schlusstext leer. Entsprechend
ist auch der Schlusstext in der Rechnung leer, d.h. beim Anlegen der
Rechnung in Collmex wird zuerst der Standard-Textbaustein gesetzt, dann
aber mit der übergebenen leeren Zeichenkette überschrieben.
Damit für Zeichenfelder das Feld nicht geändert wird, muss zur Lösung
des Problems der Wert `(NULL) `übergeben werden.
If possible, please do a short hotfix so that I can run a composer update.
=> Hotfix: Default param error within customer order and invoice regarding to Collmex conversation

src/TypeFactory.php
The Type CMXEPF / DifferentShippingAddress is created as a type but not present in the TypeFactory. 
By adding this it's possible to use CUSTOMER_RECEIVING_ADDRESS_GET
=> Added TYPE "CMXEPF" to TYPE_CLASS_MAP in TypeFactory

CHANGELOG.md, composer.json
symfony/mime is required but not listed in Composer dependencies. This PR fixes that.
=> add symfony/mime as dependency

.github/workflows/php.yml
As long as we are not collection code coverage data, we can avoid loading Xdebug and avoid the (albeit small) performance penalty.
=> Disable Xdebug on CI

.github/workflows/php.yml
This will allow us to see (and fail on) PHP notices and warnings.
=> Use the development PHP INI on CI

src/Type/Member.php, src/Type/MemberGet.php
The query ```MemberGet``` was extended by ```reporting_date``` and by the date ranges (from, to) for attributes ```entrance_date, exit_date, birthday```: 
```
entrance_date_from
entrance_date_to
exit_date_from
exit_date_to
birthday_from
birthday_to
```
Furthermore, the ```Member``` type was extended by the attribute ```no_mailings```.
=> Added new fields from Collmex API for types Member and query MemberGet

.github/dependabot.yml
We will have multi-version dependencies for the Symfony components, and Dependabot would shrink them into single-version dependencies.
=> [TASK] Block Dependabot from updating Symfony components

CHANGELOG.md, composer.json
As this project is a library, it should be installable with as many Symfony versions that still are supported in order to make it usable across as many projects as possible.
So reinstate compatibility with Symfony 5.4, and add compatibility with Symfony 7.0 and 7.1.
At the moment, Symfony 5.4, 6.4, 7.0 and 7.1 are still supported by the Symfony project:
https://symfony.com/releases
Closes #301
=> [TASK] Ensure compatibility with all supported Symfony versions
