src/TypeFactory.php
Hast du den Typen nur vergessen oder gab's ein Problem damit? 😄
=> Added missing product type

src/Type/SalesOrderGet.php
Added SalesOrderGet to fetch CMXORD-2 records.
=> added new get type

src/Type/ProductPrice.php, src/Type/ProductPriceGet.php, src/Type/Stock.php, src/Type/StockAvailable.php, src/Type/StockAvailableGet.php, src/Type/StockGet.php, src/TypeFactory.php
- ProductPrice
- ProductPriceGet
- StockAvailable
- StockAvailableGet
- Stock
- StockGet
=> Added various Types

src/Type/Customer.php, src/Type/Delivery.php, src/Type/DeliveryGet.php, src/Type/DifferentShippingAddress.php, src/TypeFactory.php
Added Types
- Delivery
- DeliveryGet
- DifferentShippingAddress
Updated Type
- Customer
=> new types and an update

src/Type/ProductPriceChange.php
With this request type, the price for the specified pricegroup will be updated, while existing prices won't be changed.
=> Added Type ProductPriceChange

src/Type/TrackingNumber.php, src/TypeFactory.php
Makes it possible to submit a tracking number to a delivery.
=> Added TrackingNumberType

CHANGELOG.md
- add additional blank lines between versions
- use HTTPS for the semver link
- limit the lines to 80 characters
=> [CLEANUP] Polish the changelog

.travis.yml
- use the container-based infrastructure
- cache Composer packages
- disable Xdebug
=> [TASK] Speed up the build

src/Response/ZipResponse.php, src/Type/AbstractType.php, src/Type/Subscription.php, tests/ResponseTest.php
- use null === instead of "is_null"
- always use parenthesis for "new"
- drop trailing backslash for "use"
=> [CLEANUP] More automated code style cleanup

tests/Csv/SimpleParserTest.php, tests/Regression/Github/2/Issue2Test.php, tests/ResponseTest.php
Always add a trailing comma after the last array element.
=> [CLEANUP] More code autoformatting

README.md, src/Type/OpenItem.php, src/Type/OpenItemsGet.php, src/TypeFactory.php
added types OpenItem, OpenItemGet
=> added types OpenItem, OpenItemGet

src/Type/AccountBalance.php
=> fix type identifier typo

src/Type/SendShipmentNotification.php
According to the [documentation](http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Versandbenachrichtigung), this request does not return an answer. Therefore no response handling type is implement.
=> Added type SendShipmentNotification

src/Type/DeliveryGet.php
New field "Versandart Nr" in the [documentation](http://www.collmex.de/cgi-bin/cgi.exe?1005,1,help,api_Lieferungen)
=> updated type DeliveryGet to comply with the docs

src/Csv/SimpleGenerator.php, src/Response/ResponseInterface.php, src/Type/AbstractType.php, tests/ResponseTest.php, tests/Type/SubscriptionTest.php, tests/Type/Validator/DateOrEmptyTest.php, tests/Type/Validator/DateTest.php, tests/Type/Validator/TimeIntervalTest.php, tests/TypeFactoryTest.php
- drop an unused import
- use single quotes whereever possible
=> [CLEANUP] More automatic code cleanup with php-cs-fixer

psalm.xml
Also autoformat the Psalm configuration file.
Closes #88
=> [TASK] Convert the Psalm warnings/notices into errors

.travis.yml
This will fix the build with PHP 7.3.
=> [BUGFIX] Make Travis more resilient for a missing Xdebug

src/Type/ShipmentConfirm.php, src/Type/StockChange.php, src/TypeFactory.php
Added StockChange type to TypeFactory and changed two fields in StockChange type.
Changing the two fields in the StockChange type should not cause any breaking issues. Since it wasn't added to the TypeFactory, it could not be used yet anyway.
=>  Added StockChange type to TypeFactory

.travis.yml, README.md, composer.json
This PR should only be merged after #106 has been merged.
=> [TASK] Sniff the code against the PSR-12 and PSR-2 rulesets in the build

.travis.yml
Before this PR can be merged, #106 needs to be merged.
=> [TASK] Re-enable Psalm in the CI build

.travis.yml, README.md, composer.json
=> [TASK] Require PHP >= 7.1

CHANGELOG.md
=> [CLEANUP] Fix typos in the changelog

src/CollmexServiceProvider.php, src/Filter/FilterInterface.php, src/Filter/Utf8ToWindows1252.php, src/Filter/Windows1252ToUtf8.php, src/Response/CsvResponse.php
@mjaschen Could you please check this with a critical eye?
=> [CLEANUP] Make some array type annotations more specific

phpcs.xml.dist, src/Type/AccountDocument.php, src/Type/AccountDocumentGet.php, src/Type/Customer.php, src/Type/CustomerOrder.php, src/Type/Delivery.php, src/Type/Invoice.php, src/Type/Member.php, src/Type/OpenItem.php, src/Type/OpenItemsGet.php, src/Type/Product.php, src/Type/PurchaseOrder.php, src/Type/Revenue.php, src/Type/SalesOrderGet.php, src/Type/StockChange.php, src/Type/StockChangeGet.php, src/TypeFactory.php
- drop surplus `@throws` annotations
- convert end-line comments
=> [CLEANUP] Streamline more comments

src/Response/CsvResponse.php
=> remove unused class property from CsvResponse

src/Csv/SimpleGenerator.php, src/Response/ZipResponse.php, src/Type/AbstractType.php, src/TypeFactory.php
Also add a missing `@return void` annotation.
=> [CLEANUP] Code autoformat

docs/collmex.adoc
The example is copied from #61 (with some modifications).
=> [TASK] Document how to transmit an order with multiple items

src/Client/AbstractClient.php, src/Type/Customer.php, src/Type/CustomerOrder.php, src/Type/Invoice.php, src/Type/InvoiceGet.php, src/Type/InvoiceOutputSet.php, src/Type/Member.php, src/Type/Product.php, src/Type/ProductGet.php, src/Type/Revenue.php, src/Type/SalesOrderGet.php, src/Type/ShipmentOrdersGet.php, src/Type/StockChange.php, src/Type/Subscription.php, src/Type/SubscriptionGet.php
=> [CLEANUP] Add type annotations for constants

tests/Integration/Response/ZipResponseTest.php
These new tests also have uncovered two bugs.
=> [TASK] Add tests for ZipResponse

tests/Unit/Csv/SimpleParserTest.php
Minify the tests and add tests for some special conditions.
The LeageCsvParser test is not changed as that class will be removed soon.
=> [TASK] Rework the simple CSV parser test

tests/Integration/Response/ZipResponseTest.php
=> [BUGFIX] Fix test failure due to renamed test variable

src/CollmexServiceProvider.php, src/Csv/SimpleGenerator.php
This will slightly improve performance.
=> [TASK] Make closures static

src/Client/AbstractClient.php
=> [BUGFIX] Update the Collmex API URL

CHANGELOG.md
I've updated the change log for the upcoming release. @oliverklee can you take a look if everything looks fine?
=> Update change log for release 1.0

src/Type/ProductionOrder.php, src/Type/ProductionOrderGet.php, src/TypeFactory.php, tests/Unit/Type/ProductionOrderGetTest.php, tests/Unit/Type/ProductionOrderTest.php
[Documentation ProductionOrderGet](http://www.collmex.de/c.cmx?1005,1,help,api_Produktionsauftraege)
[Documentation ProductionOrder](http://www.collmex.de/c.cmx?1005,1,help,daten_importieren_produktionsauftraege)
=> feat: added type ProductionOrder

src/Type/Voucher.php, src/Type/VoucherGet.php, src/TypeFactory.php, tests/Unit/Type/VoucherTest.php
=> added Voucher type

docs/collmex.adoc
Added description for order id and number generation
=> Updated doc

README.md, src/Type/InvoiceOutput.php, src/TypeFactory.php
=> Add new API endpoint for sending invoices

src/Type/BankStatementGet.php, src/Type/InvoicePayment.php, src/Type/InvoicePaymentGet.php, src/TypeFactory.php, tests/Unit/Type/BankStatementGetTest.php, tests/Unit/Type/InvoicePaymentGetTest.php, tests/Unit/Type/InvoicePaymentTest.php
Hallo Marcus,
ich habe die beiden Satzarten INVOICE_PAYMENT und INVOICE_PAYMENT_GET hinzugefügt.
Lass mich gerne wissen, wenn du Anmerkungen hast.
Viele Grüße,
Lukas
=> Add InvoicePayment and InvoicePaymentGet

README.md
Hi @mjaschen
I prepared adaptions of the README.md
=> Adapt README.md regarding numeric array values format (#236)

README.md, src/Type/SupplierCredit.php, src/TypeFactory.php
Added a new type for creating credit notes (reversed invoices) for a supplier as described here: http://www.collmex.de/c.cmx?1005,1,help,daten_importieren_gutschriften_an_lieferant
=> Add SupplierCredit type

CHANGELOG.md, src/Type/CustomerOrder.php
- rename `reserved_2` to `voucher`
- add `different_recipient` and `relevant_for_delivery`
=> add/update fields for Customer Order

CHANGELOG.md, src/Type/CustomerOrder.php
=> add docblock lines for new fields
